# Generated by Django 4.0.8 on 2026-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hi',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
