# Generated by Django 4.0.8 on 2026-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_es',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_fr',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text_hi',
            field=models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_hi',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_hi',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_hi',
            field=models.TextField(blank=True, help_text='A detailed description of the quiz', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_hi',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
